### PR TITLE
Implement cooperative preemption for lua.

### PR DESCRIPTION
**Pull request by postwait**

### CODE REVIEW

**Comment by HeinrichHartmann** [comment]
As discussed on Slack: I quite like to have the option to throw lua errors, in case of watchdog timeouts. This gives a very effective way to debug issues where lua hogs the CPU. If we re-schedule always, we loose this capability.

**Comment by HeinrichHartmann** [comment]
I played around with this a little more:

Calling mtev.interrupt_hook() too early (e.g. snowth-init) fails with ("coro terminated"). Setting the hook form the request handler works.

Fully jit-ed functions can not be pre-empted:
```
  -- use infinite CPU
  if qs.cpu_bomb then
    -- play Collatz game
    local i = 1
    while true do
      if i % 2 == 0 then
        i = i / 2
        --- mtev.log("debug", "x")
      else
        --- mtev.log("debug", "o")
        i = 3*i + 1
      end
    end
  end
```
In this case the hook ("lstop") will not be called.

Uncommenting those two log lines, we are calling the hook, but pre-emption will fail with: `lua/test_error: attempt to yield across C-call boundary`

Thorowing an error from the lua interrupt_hook, works nicely in this case.
Also printing a stack trace `debug.traceback()` works fine.

**Comment by HeinrichHartmann** [comment]
Here is another error, without a mtev.interrupt_hook set, calling the cpu_bomb function _sometimes_ crashes the process with:

```
192.168.2.201 - - [23/Jan/2020:20:13:12 -0000] "GET /extension/lua/test_error?cpu_bomb=1 HTTP/1.1" 500 634|0 1011.583
XXX mtev lua open
Using lualib_path=/home/hhartmann/circ/src/snowth/src/lua/extensions/?.lua;/home/hhartmann/circ/src/snowth/src/lua/support/?.lua;/home/hhartmann/circ/src/snowth/src/lua/test/?.lua;/home/hhartmann/circ/src/snowth/src/?.lua;
coro_store -> 0x7fc1401cabd0
loading luamtev-extension
Starting lua timer: 0x7fc19800c4e8 for 1.000000
Handling request to lua module 'test_error'
XXX HANDLER START
timer fired: lua 0x7fc1401cabd0
LSTOP fired!
lua state 0x7fc1401cabd0 preempted
register_event( in: 0x7fc1401cabd0 , e: 0x7fc19800d7e0 )
lua: 0x7fc1401cabd0 yielding
Stopping lua timer: 0x7fc19800c4e8
deregister_event( in: 0x7fc1401cabd0 , e: 0x7fc19800d7e0 )
Starting lua timer: 0x7fc19800c4e8 for 1.000000
emancipate: process 23435, monitored 23435, signal 11
[monitor] snowth 23435 has stopped.
[monitor] snowth 23435 has crashed.
STACKTRACE(23435):
t@23449> 0000000000000003
t@23449> -- mtev lua runtime stacktrace --
t@23449> stack traceback:
t@23449> 	[C]: in function 'log'
t@23449> 	...rtmann/circ/src/snowth/src/lua/extensions/test_error.lua:65: in function <...rtmann/circ/src/snowth/src/lua/extensions/test_error.lua:4>
t@23449> 	[C]: in function 'xpcall'
t@23449> 	...hartmann/circ/src/snowth/src/lua/support/snowth-init.lua:311: in function 'extension_process'
t@23449> 	...nn/circ/src/snowth/src/lua/support/luamtev-extension.lua:118: in function <...nn/circ/src/snowth/src/lua/support/luamtev-extension.lua:78>
t@23449> 
[monitor] reaped pid: 23435.
[monitor] snowth child died [0/17], restarting.

```

**Comment by HeinrichHartmann** [comment]
I'll stop debugging this for now.

**Comment by postwait** [comment]
This is addressed in #804 and enabling by default is pending some luajit issue resolution.

**Pull request closed without merging**
