### PR TITLE
Suppress GCC 7 warnings for "-Wimplicit-fallthrough" and "-Wclobbered"

### PR DESCRIPTION
**Pull request by cody271**
Fixes `libmtev` build with GCC 7 on newer Ubuntu. (Follow up to PR #370)

### CODE REVIEW

**Comment by postwait** [comment]
Another option is to fix the code. What would that look like?

**Comment by cody271** [comment]
For `-Wimplicit-fallthrough`, it looks these are all valid uses of fall through in a switch statement.

Personally I think warning suppression with `#pragma` is much clearer than using the special comment `/* fall through */`. Though we actually are already using that [here](https://github.com/circonus-labs/libmtev/blob/master/src/utils/mtev_watchdog.c#L735).. thoughts?

**Comment by cody271** [comment]
For `-Wclobbered`, there we could be an actual bug there. I don't honestly understand the code in [`eventer_jobq_consumer()`](https://github.com/circonus-labs/libmtev/blob/master/src/eventer/eventer_jobq.c#L697) enough to know for sure. 

Documentation for that warning recommends adding `volatile`, but that shouldn't be necessary here and actually conflicts with `libck` primitives.

**Comment by postwait** [comment]
I think the advantage of the `/* fall through */` comment is that is must be specified at use (per-case) whereas the pragma tends to wrap the whole switch.  I think we should comment.

**Comment by postwait** [comment]
As for the clobber, since we use ck all over the place and this is the only warning site, we should figure out what's going on b/c the warning could be a real indicator of a flaw.

**Pull request merged**
