### PR TITLE
Prevent javascript from adding thousands of lines of log to Internals…

### PR DESCRIPTION
**Pull request by vasuraman11**

### CODE REVIEW

**Comment by vasuraman11** [comment]
I think the libmtev build is creating the minimized version of the js'es but I also saw it seems the minimized file is also committed.  Should I try to run the build and commit the minimized version, or should I let this be done by CI?

**Comment by postwait** [comment]
CI won't do that.

**Comment by rileyberton** [comment]
Yeah, I think we need to compile and check in the minimized version

**Comment by vasuraman11** [comment]
This PR relates to part of CIRC-1525 (addressing the responsiveness issues but not collapse/expand).

**Comment by vasuraman11** [comment]
Merging the fix and closing.

**Pull request merged**
