### PR TITLE
Version 2.6.0

### PR DESCRIPTION
**Pull request by pamaddox**

### CODE REVIEW

**Comment by esproul** [comment]
Wondering if this merits a minor version bump; according to semver: "when you add functionality in a backward compatible manner", which sounds like what we're doing. Thoughts on making this 2.6.0?

**Review by bdunavant — APPROVED** [review]
LGTM - I don't have an opinion about the semver

**Comment by pamaddox** [comment]
Changed to 2.6.0

**Review by esproul — APPROVED** [review]
LGTM, thanks

**Pull request merged**
